from PIL import Image, ImageDraw, ImageFont
from collections import deque
from pathlib import Path

# Local python modules
from ..common_utils import (
    config,
    logger,
    conditional_inject_spinner,
)
from yaspin.core import Yaspin
from yaspin.spinners import Spinners

REGULAR_INDEX = 0
BOLD_INDEX = 1
ITALIC_INDEX = 2
LIGHT = {"fill": (0, 0, 0, 255), "stroke_fill": None, "stroke_width": 0}
DARK = {"fill": (255, 255, 255, 255), "stroke_fill": None, "stroke_width": 0}
BOTH_8PX = {
    "fill": (255, 255, 255, 255),
    "stroke_fill": (0, 0, 0, 255),
    "stroke_width": 8,
}
MSCP_GREEN = (41, 99, 54, 255)
PLATFORMS = ["macOS", "iOS", "visionOS"]
PLATFORM_COLORS = {
    "macOS": (41, 99, 54, 255),
    "iOS": (88, 86, 214, 255),
    "visionOS": (255, 45, 85, 255),
}
SUFFIX = "Security Configuration Guide"
SUBTITLE = "as generated by the macOS Security Compliance Project"
MODES = {"light": LIGHT, "dark": DARK, "both_8px": BOTH_8PX}
FONT = "HelveticaNeue.ttc"


def color_dist(a, b):
    return sum(abs(a[i] - b[i]) for i in range(3))


def isolate_logo(logo_path: str, threshold: int = 40) -> Image.Image:
    img = Image.open(logo_path).convert("RGBA")
    w, h = img.size
    pix = img.load()
    bg = img.getpixel((0, 0))
    visited = [[False] * w for _ in range(h)]
    q = deque()
    for x in range(w):
        for y in (0, h - 1):
            if not visited[y][x] and color_dist(pix[x, y], bg) <= threshold:
                visited[y][x] = True
                q.append((x, y))
    for y in range(h):
        for x in (0, w - 1):
            if not visited[y][x] and color_dist(pix[x, y], bg) <= threshold:
                visited[y][x] = True
                q.append((x, y))
    while q:
        x, y = q.popleft()
        for nx, ny in ((x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)):
            if 0 <= nx < w and 0 <= ny < h and not visited[ny][nx]:
                if color_dist(pix[nx, ny], bg) <= threshold:
                    visited[ny][nx] = True
                    q.append((nx, ny))
    out = img.copy()
    opix = out.load()
    for y in range(h):
        for x in range(w):
            if visited[y][x]:
                opix[x, y] = (0, 0, 0, 0)
    bbox = out.getchannel("A").getbbox()
    return out.crop(bbox)


def font(
    font_path: str, size: int, bold: bool = False, italic: bool = False
) -> ImageFont.FreeTypeFont:
    index = ITALIC_INDEX if italic else (BOLD_INDEX if bold else REGULAR_INDEX)
    return ImageFont.truetype(font_path, size, index=index)


def draw_text(draw, xy, text: str, fnt, style: dict):
    kwargs = {"font": fnt, "fill": style["fill"]}
    if style.get("stroke_fill") is not None and style.get("stroke_width", 0) > 0:
        kwargs["stroke_fill"] = style["stroke_fill"]
        kwargs["stroke_width"] = style["stroke_width"]
    draw.text(xy, text, **kwargs)


def change_color(image, old_color, new_color, tolerance=0) -> Image.Image:
    pixels = image.load()
    width, height = image.size

    for y in range(height):
        for x in range(width):
            r, g, b, a = pixels[x, y]

            # Skip fully transparent pixels
            if a == 0:
                continue

            # Check if pixel matches target color within tolerance
            if (
                abs(r - old_color[0]) <= tolerance
                and abs(g - old_color[1]) <= tolerance
                and abs(b - old_color[2]) <= tolerance
            ):
                pixels[x, y] = new_color  # Keep original alpha

    return image


@conditional_inject_spinner()
def generate_mscp_banners(sp: Yaspin, *args) -> None:
    logger.info("Generating MSCP banners...")
    sp.spinner = Spinners.dots
    sp.text = "Generating MSCP banners"

    outdir = Path(config["images_dir"])
    logo = isolate_logo(Path(config["images_dir"]) / "mscp_logo.png")

    # define width and height of the final banner; the logo will be resized to fit within this while leaving room for text
    H = 420

    # Load fonts
    platform_font = font(FONT, 72, bold=True, italic=False)
    suffix_font = font(FONT, 62, bold=False, italic=False)
    subtitle_font = font(FONT, 24, bold=False, italic=True)

    probe = Image.new("RGBA", (10, 10), (0, 0, 0, 0))
    dp = ImageDraw.Draw(probe)

    max_platform_h = 0

    platform_widths = {}
    platform_heights = {}
    for p in PLATFORMS:
        bb = dp.textbbox((0, 0), p, font=platform_font)
        platform_widths[p] = bb[2] - bb[0]
        platform_heights[p] = bb[3] - bb[1]
        max_platform_h = max(max_platform_h, platform_heights[p])

    suffix_bb = dp.textbbox((0, 0), SUFFIX, font=suffix_font)
    suffix_h = suffix_bb[3] - suffix_bb[1]
    suffix_w = suffix_bb[2] - suffix_bb[0]

    gap_between = 22
    block_h = max_platform_h + gap_between + suffix_h

    lw, lh = logo.size
    new_height = H - 40
    new_width = int(lw * (new_height / lh))

    logo_resized = logo.resize((new_width, new_height), Image.LANCZOS)

    lx = 110
    ly = (H - logo_resized.height) // 2
    left_margin = lx + logo_resized.width + 70
    top_y = ly + (logo_resized.height - block_h) // 2 + 10

    text_block_h = max(max(platform_heights.values()), suffix_h)
    platform_y = (H - text_block_h) // 2 - 6
    suffix_y = platform_y + 8

    # define divider properties
    divider_gap_left = 25
    divider_gap_right = 25
    divider_width = 8
    divider_h = 92
    divider_y = (H - divider_h) // 2 + 8

    created = []
    for p in PLATFORMS:
        logger.info(f"Generating banner for {p}...")
        _pw = platform_widths[p]

        divider_x = left_margin + _pw + divider_gap_left
        suffix_x = divider_x + divider_gap_right + divider_width

        colored_logo = logo_resized.copy()
        colored_logo = change_color(
            colored_logo,
            MSCP_GREEN[:3],
            PLATFORM_COLORS.get(p, MSCP_GREEN[:3]),
            tolerance=25,
        )

        for mode_name, style in MODES.items():
            canvas_width = (
                left_margin
                + _pw
                + divider_gap_left
                + divider_width
                + divider_gap_right
                + suffix_w
                + 40
            )
            canvas = Image.new("RGBA", (canvas_width, H), (0, 0, 0, 0))
            draw = ImageDraw.Draw(canvas)
            canvas.alpha_composite(colored_logo, (lx, ly))
            draw_text(draw, (left_margin, platform_y), p, platform_font, style)
            draw.rounded_rectangle(
                (
                    divider_x,
                    divider_y,
                    divider_x + divider_width,
                    divider_y + divider_h,
                ),
                fill=PLATFORM_COLORS.get(p, MSCP_GREEN),
                radius=divider_width // 2,
            )
            draw_text(draw, (suffix_x, suffix_y), SUFFIX, suffix_font, style)
            draw_text(
                draw,
                (left_margin, top_y + divider_h + gap_between),
                SUBTITLE,
                subtitle_font,
                style,
            )
            out = outdir / f"mscp_banner_{p.lower()}_{mode_name}.png"
            canvas.save(out)
            created.append(out)

    logger.info(f"Created {len(created)} files in {outdir}")
    sp.text = f"Created {len(created)} files in {outdir}"
    sp.ok("✔")
