== Contributing

=== Engage
Contribute new content, share feedback and ask questions about resources in the repository using the https://github.com/usnistgov/macos_security/issues/new[Issues feature].

=== Operating Rules
These operating rules describe and govern NIST’s management of this repository and contributors’ responsibilities. NIST reserves the right to modify this policy at any time.

=== Criteria for Contributions and Feedback
This is a moderated platform. NIST will only accept contributions that are contributed per the terms of the license file. Contributors may submit links or materials for hosting in the repository. Upon submission, materials will be public and considered publicly available information, unless noted in the license file. 

NIST reserves the right to reject, remove, or edit any contribution or feedback, including anything that: 
* states or implies NIST endorsement of any entities, services, or products;  
* is inaccurate;  
* contains abusive or vulgar content, spam, hate speech, personal attacks, or similar content;  
* is clearly "off topic"; 
* makes unsupported accusations;
* includes personally identifiable or business identifiable information according to Department of Commerce Office of Privacy and Open Government (http://www.osec.doc.gov/opog/privacy/PII_BII.html[guidelines]; or, 
* contains .exe or .jar file types.

_These file types will not be hosted in the NIST repository; instead, NIST may link to these if hosted elsewhere._

=== Contributor Responsibilities
NIST also reserves the right to reject or remove contributions from the repository if the contributor fails to carry out any of the following responsibilities:

* following the contribution instructions;
* responding to feedback from other repository users in a timely manner;
* responding to NIST representatives in a timely manner;
* keeping contributions and contributor GitHub username up to date

*GitHub Help:* If you're having trouble with these instructions, and need more information about GitHub, pull requests, and issues, visit GitHub's Help https://help.github.com/categories/collaborating-with-issues-and-pull-requests/[page]. 
